@PEP_HostAddress = http://localhost:5010

GET {{PEP_HostAddress}}/api/Courses
Accept: application/json

###查询全部课程信息
GET {{PEP_HostAddress}}/api/Courses/User/1
Accept: application/json
###查询某用户的课程信息
GET {{PEP_HostAddress}}/api/Courses/User/4
Accept: application/json
###查询不存在的用户的课程信息

GET {{PEP_HostAddress}}/api/Courses/21
Accept: application/json
###查询单个课程信息

POST {{PEP_HostAddress}}/api/Courses