@PEP_HostAddress = http://localhost:5010

GET {{PEP_HostAddress}}/api/Courses
Accept: application/json

###测试全部课程信息
GET {{PEP_HostAddress}}/api/Courses/User/1
Accept: application/json
###测试单个课程信息
GET {{PEP_HostAddress}}/api/Courses/User/4
Accept: application/json
###测试不存在的课程信息